### ISSUE TITLE
Create DataValues for every DataType when you construct add Project Years

### ISSUE THREAD

**Issue by chenhoward** [calblueprint/CRT#103]
Right now, when we construct Project Years we don't construct the Empty Data Values with it so our tables are not aligned.  On the construction of Project Years (on both add year and on creation), we should initialize DataValues for every DataType for the project years we create.  If it is a formula, initialize as nil, but if it is a value initialize at 0.  @andylouisqin lmk if that is right.  Only do it for the nonMaster projects and nonMaster data types for now.

**Comment by andylouisqin** [comment]
Seems right with the exception of formulas using `.prev`. We wouldn't want to initialize those as `nil` since the whole row would be `nil` if each value relies on its previous year's value. Instead initialize those to 0 along with values.
