### ISSUE TITLE
Error when setting cell formula

### ISSUE THREAD

**Issue by ottopchen** [calblueprint/CRT#184]
A patch error occurs when trying to assign formulas with spaces to cells. For example, trying to set a Cell to "Up Front" or "Admin Draw" will cause an error, while formulas like "PAR" and "Net" work fine.

**Comment by chenhoward** [comment]
Try adding underscores to the formula instead of spaces

**Comment by chenhoward** [comment]
@ottopchen did the underscores make the formula work?

**Comment by ottopchen** [comment]
Yea it worked
