### ISSUE TITLE
Data Types Ordering and Edit order

### ISSUE THREAD

**Issue by kevintxwu** [calblueprint/CRT#31]

**Comment by jodreen** [comment]
Don't worry about this for now, not part of our MVP

**Comment by chenhoward** [comment]
DataTypes are inherently unordered.  We want to be able to order them to allow the user to organize their data values.

## Possible ways to do this:
1. Assign an integer value to a task
2. Do a calculation to generate a float.  A little more complicated but interesting if we have the time and has some benefits.

**Comment by jodreen** [comment]
I would say this is really low priority; it's something we talked about briefly, but ultimately decided it wasn't worth building out. Can even be deleted
