### ISSUE TITLE
Change slim to erb for application.html

### ISSUE THREAD

**Issue by jodreen** [calblueprint/CRT#33]
so it don't look like shit

![screen shot 2015-10-21 at 6 36 32 pm](https://cloud.githubusercontent.com/assets/3992611/10654712/b3c98e22-7822-11e5-9765-6a231491b30a.png)

**Comment by jodreen** [comment]
closed https://github.com/calblueprint/CRT/pull/40

**Comment by kevintxwu** [comment]
wtf is application.html...do you even code????

**Comment by kevintxwu** [comment]
.e r b

**Comment by jodreen** [comment]
:disappointed:
