### ISSUE TITLE
Parsing formulas

### ISSUE THREAD

**Issue by jodreen** [calblueprint/CRT#44]
1. validate
2. parse
3. recalculate all data values for all years :0

every time the project show page is loaded, the data values with data types that use formulas should be recalculated (and saved if different than stored value)

fun

this looks promising?!?! https://github.com/rubysolo/dentaku

**Comment by kevintxwu** [comment]
e z

**Comment by jodreen** [comment]
https://github.com/calblueprint/CRT/pull/58
